//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _16.slide.puzzle.game.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_16.slide.puzzle.game.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blankslide {
            get {
                object obj = ResourceManager.GetObject("blankslide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gettyimages_73539607_612x612_01 {
            get {
                object obj = ResourceManager.GetObject("gettyimages-73539607-612x612_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gettyimages_73539607_612x612_02 {
            get {
                object obj = ResourceManager.GetObject("gettyimages-73539607-612x612_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gettyimages_73539607_612x612_021 {
            get {
                object obj = ResourceManager.GetObject("gettyimages-73539607-612x612_021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gettyimages_73539607_612x612_03 {
            get {
                object obj = ResourceManager.GetObject("gettyimages-73539607-612x612_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gettyimages_73539607_612x612_04 {
            get {
                object obj = ResourceManager.GetObject("gettyimages-73539607-612x612_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gettyimages_73539607_612x612_05 {
            get {
                object obj = ResourceManager.GetObject("gettyimages-73539607-612x612_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gettyimages_73539607_612x612_06 {
            get {
                object obj = ResourceManager.GetObject("gettyimages-73539607-612x612_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gettyimages_73539607_612x612_07 {
            get {
                object obj = ResourceManager.GetObject("gettyimages-73539607-612x612_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gettyimages_73539607_612x612_08 {
            get {
                object obj = ResourceManager.GetObject("gettyimages-73539607-612x612_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gettyimages_73539607_612x612_09 {
            get {
                object obj = ResourceManager.GetObject("gettyimages-73539607-612x612_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gettyimages_73539607_612x612_091 {
            get {
                object obj = ResourceManager.GetObject("gettyimages-73539607-612x612_091", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gettyimages_73539607_612x612_10 {
            get {
                object obj = ResourceManager.GetObject("gettyimages-73539607-612x612_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gettyimages_73539607_612x612_11 {
            get {
                object obj = ResourceManager.GetObject("gettyimages-73539607-612x612_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gettyimages_73539607_612x612_12 {
            get {
                object obj = ResourceManager.GetObject("gettyimages-73539607-612x612_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gettyimages_73539607_612x612_13 {
            get {
                object obj = ResourceManager.GetObject("gettyimages-73539607-612x612_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gettyimages_73539607_612x612_14 {
            get {
                object obj = ResourceManager.GetObject("gettyimages-73539607-612x612_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jay_crtich_did_it_again_fashion_interview__1__01 {
            get {
                object obj = ResourceManager.GetObject("jay-crtich-did-it-again-fashion-interview-(1)_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jay_crtich_did_it_again_fashion_interview__1__02 {
            get {
                object obj = ResourceManager.GetObject("jay-crtich-did-it-again-fashion-interview-(1)_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jay_crtich_did_it_again_fashion_interview__1__03 {
            get {
                object obj = ResourceManager.GetObject("jay-crtich-did-it-again-fashion-interview-(1)_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jay_crtich_did_it_again_fashion_interview__1__04 {
            get {
                object obj = ResourceManager.GetObject("jay-crtich-did-it-again-fashion-interview-(1)_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jay_crtich_did_it_again_fashion_interview__1__05 {
            get {
                object obj = ResourceManager.GetObject("jay-crtich-did-it-again-fashion-interview-(1)_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jay_crtich_did_it_again_fashion_interview__1__051 {
            get {
                object obj = ResourceManager.GetObject("jay-crtich-did-it-again-fashion-interview-(1)_051", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jay_crtich_did_it_again_fashion_interview__1__06 {
            get {
                object obj = ResourceManager.GetObject("jay-crtich-did-it-again-fashion-interview-(1)_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jay_crtich_did_it_again_fashion_interview__1__07 {
            get {
                object obj = ResourceManager.GetObject("jay-crtich-did-it-again-fashion-interview-(1)_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jay_crtich_did_it_again_fashion_interview__1__08 {
            get {
                object obj = ResourceManager.GetObject("jay-crtich-did-it-again-fashion-interview-(1)_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jay_crtich_did_it_again_fashion_interview__1__09 {
            get {
                object obj = ResourceManager.GetObject("jay-crtich-did-it-again-fashion-interview-(1)_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jay_crtich_did_it_again_fashion_interview__1__10 {
            get {
                object obj = ResourceManager.GetObject("jay-crtich-did-it-again-fashion-interview-(1)_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jay_crtich_did_it_again_fashion_interview__1__11 {
            get {
                object obj = ResourceManager.GetObject("jay-crtich-did-it-again-fashion-interview-(1)_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jay_crtich_did_it_again_fashion_interview__1__12 {
            get {
                object obj = ResourceManager.GetObject("jay-crtich-did-it-again-fashion-interview-(1)_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jay_crtich_did_it_again_fashion_interview__1__13 {
            get {
                object obj = ResourceManager.GetObject("jay-crtich-did-it-again-fashion-interview-(1)_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jay_crtich_did_it_again_fashion_interview__1__14 {
            get {
                object obj = ResourceManager.GetObject("jay-crtich-did-it-again-fashion-interview-(1)_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jay_crtich_did_it_again_fashion_interview__1__15 {
            get {
                object obj = ResourceManager.GetObject("jay-crtich-did-it-again-fashion-interview-(1)_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
